"""reestruturacao_completa_doc2

Revision ID: 8333d49194f3
Revises: 
Create Date: 2026-07-24 10:33:50.352571

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8333d49194f3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='Hash bcrypt/argon2 da senha'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('worlds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('articles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('world_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('visibility', sa.Enum('TOTAL', 'PARCIAL', 'NULA', name='visibility_type'), nullable=False),
    sa.Column('in_game_date', sa.String(length=50), nullable=True, comment="Data fictícia do mundo (ex: '1442 D.C.')"),
    sa.Column('in_game_sort_order', sa.BigInteger(), nullable=True, comment='Inteiro normalizado para ordenação na Timeline'),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_articles_timeline', 'articles', ['world_id', 'in_game_sort_order'], unique=False, postgresql_where='in_game_sort_order IS NOT NULL')
    op.create_index('idx_articles_world_visibility', 'articles', ['world_id', 'visibility'], unique=False)
    op.create_table('manuscripts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('world_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('world_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False, comment='Caminho do arquivo de imagem otimizado (WebP/JPG)'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timeline_eras',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('world_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False, comment="Nome da era (ex: 'Segunda Era da Magia')"),
    sa.Column('start_sort_order', sa.BigInteger(), nullable=False, comment='Valor de ordem inicial da era'),
    sa.Column('end_sort_order', sa.BigInteger(), nullable=False, comment='Valor de ordem final da era'),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('world_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('world_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('MESTRE', 'JOGADOR', name='user_role'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('world_id', 'user_id', name='unique_world_user')
    )
    op.create_table('article_sections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('content', sa.Text(), server_default='', nullable=False, comment='Conteúdo da seção — suporta Markdown e @Mentions'),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article_tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='Nome da tag (ex: .Hostil, .NPC, .Facção)'),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_article_tags_article', 'article_tags', ['article_id'], unique=False)
    op.create_index('idx_article_tags_name', 'article_tags', ['name'], unique=False)
    op.create_table('character_inventories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('item_name', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manuscript_chapters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('manuscript_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('content', sa.Text(), server_default='', nullable=False, comment='Texto do resumo — suporta Markdown e @Mentions'),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('visibility', sa.Enum('TOTAL', 'PARCIAL', 'NULA', name='visibility_type'), nullable=False),
    sa.ForeignKeyConstraint(['manuscript_id'], ['manuscripts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('map_layers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('map_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment="Nome da camada (ex: 'Cidades', 'Rotas de Comércio')"),
    sa.Column('is_default_active', sa.Boolean(), nullable=False, comment='Se a camada vem visível por padrão'),
    sa.ForeignKeyConstraint(['map_id'], ['maps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('map_pins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('map_id', sa.UUID(), nullable=False),
    sa.Column('layer_id', sa.UUID(), nullable=True),
    sa.Column('target_article_id', sa.UUID(), nullable=True, comment='Link para artigo da wiki (opcional)'),
    sa.Column('target_map_id', sa.UUID(), nullable=True, comment='Link para sub-mapa aninhado (opcional)'),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('x_position', sa.Numeric(precision=5, scale=2), nullable=False, comment='Coordenada X relativa em % (0 a 100)'),
    sa.Column('y_position', sa.Numeric(precision=5, scale=2), nullable=False, comment='Coordenada Y relativa em % (0 a 100)'),
    sa.Column('icon', sa.String(length=50), server_default='default-pin', nullable=False),
    sa.Column('color', sa.String(length=7), server_default='#FF0000', nullable=False, comment='Código hexadecimal de cor'),
    sa.Column('visibility', sa.Enum('TOTAL', 'PARCIAL', 'NULA', name='visibility_type'), nullable=False),
    sa.CheckConstraint('x_position BETWEEN 0 AND 100', name='ck_pin_x_range'),
    sa.CheckConstraint('y_position BETWEEN 0 AND 100', name='ck_pin_y_range'),
    sa.ForeignKeyConstraint(['layer_id'], ['map_layers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['map_id'], ['maps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_article_id'], ['articles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_map_id'], ['maps.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_map_pins_map_visibility', 'map_pins', ['map_id', 'visibility'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_map_pins_map_visibility', table_name='map_pins')
    op.drop_table('map_pins')
    op.drop_table('map_layers')
    op.drop_table('manuscript_chapters')
    op.drop_table('character_inventories')
    op.drop_index('idx_article_tags_name', table_name='article_tags')
    op.drop_index('idx_article_tags_article', table_name='article_tags')
    op.drop_table('article_tags')
    op.drop_table('article_sections')
    op.drop_table('world_members')
    op.drop_table('timeline_eras')
    op.drop_table('maps')
    op.drop_table('manuscripts')
    op.drop_index('idx_articles_world_visibility', table_name='articles')
    op.drop_index('idx_articles_timeline', table_name='articles', postgresql_where='in_game_sort_order IS NOT NULL')
    op.drop_table('articles')
    op.drop_table('worlds')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
